name: candle_reader_example
description: Demo app for the candle_reader package.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  candle_reader:
    path: ../

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
